# Gitpod configuration for Hello Claude Demo
# This file configures the Gitpod workspace for optimal development experience

# Use Python 3.9 image for consistency with other platforms
image: gitpod/workspace-full:latest

# Install system dependencies
tasks:
  - name: Setup Python Environment
    init: |
      # Upgrade pip
      pip install --upgrade pip
      
      # Install project dependencies globally (easier for Gitpod)
      pip install -r requirements.txt
      
      # Install development tools
      pip install black flake8 isort pylint
      
      echo "🚀 Hello Claude Demo environment is ready!"
      echo "💡 Set your ANTHROPIC_API_KEY: export ANTHROPIC_API_KEY='your-api-key-here'"
      echo "🎯 Try: ./web.sh (web app opens automatically in browser!)"
    command: |
      echo "✅ Using global Python installation"
      echo "Environment setup complete! You can now run the demo."
      echo "Remember to set your ANTHROPIC_API_KEY environment variable."

# Configure VS Code extensions for better development experience
vscode:
  extensions:
    - ms-python.python
    - ms-python.black-formatter
    - ms-python.flake8
    - ms-python.isort
    - ms-python.pylint
    - ms-vscode.vscode-json
    - redhat.vscode-yaml
    - ms-vscode.makefile-tools
    - ms-vscode.vscode-markdownlint

# Environment variables (users will need to set ANTHROPIC_API_KEY)
env:
  PYTHONPATH: "${GITPOD_REPO_ROOT}"
  PYTHONUNBUFFERED: "1"

# Configure Git
gitConfig:
  user.email: "gitpod@example.com"
  user.name: "Gitpod User" 